### ISSUE TITLE
`as of now` clause crash

### ISSUE THREAD

**Issue by kevgs** [tempesta-tech/mariadb#398] opened 2017-12-14 14:28 UTC
### Reproduce
```sql
CREATE TABLE `t` (
  `x` int(11) NOT NULL,
  `y` int(11) DEFAULT NULL WITHOUT SYSTEM VERSIONING,
  `sys_trx_start` bigint(20) unsigned GENERATED ALWAYS AS ROW START,
  `sys_trx_end` bigint(20) unsigned GENERATED ALWAYS AS ROW END,
  PRIMARY KEY (`x`,`sys_trx_end`),
  PERIOD FOR SYSTEM_TIME (`sys_trx_start`, `sys_trx_end`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 WITH SYSTEM VERSIONING;

insert into t values (2, NULL);

select * from t for system_time as of current_timestamp;
select * from t for system_time as of now;
```

### Result
```
#4  Item_field::type_handler (this=0x7f4adc015160) at item.h:2821
#5  Item::result_type (this=0x7f4adc015160) at item.h:817
#6  vers_select_conds_t::resolve_units (this=0x7f4adc015878, timestamps_only=false) at table.cc:8882
#7  st_select_lex::vers_setup_conds (this=0x7f4adc005230, thd=0x7f4adc000d50, tables=0x7f4adc015270, where_expr=0x7f4adc015da0) at sql_select.cc:898
#8  JOIN::prepare (this=0x7f4adc015998, tables_init=0x7f4adc015270, wild_num=1, conds_init=0x0, og_num=0, order_init=0x0, skip_order_by=false, group_init=0x0, having_init=0x0, proc_param_init=0x0, select_lex_arg=0x7f4adc005230, unit_arg=0x7f4adc004ad0) at sql_select.cc:1114
#9  mysql_select (thd=0x7f4adc000d50, tables=0x7f4adc015270, wild_num=1, fields=List<Item> with 1 elements, conds=0x0, og_num=0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=2147748608, result=0x7f4adc015978, unit=0x7f4adc004ad0, select_lex=0x7f4adc005230) at sql_select.cc:4183
#10 handle_select (thd=0x7f4adc000d50, lex=0x7f4adc004a08, result=0x7f4adc015978, setup_tables_done_option=0) at sql_select.cc:368
#11 execute_sqlcom_select (thd=0x7f4adc000d50, all_tables=0x7f4adc015270) at sql_parse.cc:6532
#12 mysql_execute_command (thd=0x7f4adc000d50) at sql_parse.cc:3749
#13 mysql_parse (thd=0x7f4adc000d50, rawbuf=0x7f4adc014f48 "select * from t for system_time as of now", length=41, parser_state=0x7f4b2c1ac410, is_com_multi=false, is_next_command=false) at sql_parse.cc:7988
```

### Expected
At a bare minimum it should not crash. Also, `now` is a kind of an alias of `current_timestamp` in MariaDB.

**Comment by midenok** [comment] 2017-12-14 15:06
Duplicate of #397.

**Closed as completed** 2017-12-14 15:43 UTC
Labels: bug
