### ISSUE TITLE
incorrect results for SYSTEM_TIME queries in DDL SURVIVE mode

### ISSUE THREAD

**Issue by kevgs** [tempesta-tech/mariadb#277] opened 2017-10-04 10:21 UTC
```sql
set versioning_alter_history = survive;
create or replace table t (a int) with system versioning;
insert into t values (1);
set @ts1 = now(6);
alter table t add column b int;
update t set a=2;
set @ts2 = now(6);
alter table t drop column b;
update t set a = 3;
select * from t for system_time all;
a	sys_trx_start	sys_trx_end
1	2017-10-04 13:18:03.995771	2017-10-04 13:18:03.996839
select * from t;
a
3
select * from t for system_time as of now;
a
3
select * from t for system_time as of timestamp now(6);
a
3
select * from t for system_time as of @ts1;
a
1
select * from t for system_time from '0-0-0' to now(6);
a	sys_trx_start	sys_trx_end
1	2017-10-04 13:18:03.995771	2017-10-04 13:18:03.996839
select * from t for system_time between '0-0-0' and now(6);
a	sys_trx_start	sys_trx_end
```

These has **incorrect** results:
```
select * from t for system_time all;
select * from t for system_time from '0-0-0' to now(6);
select * from t for system_time between '0-0-0' and now(6);
```
**Expected** results are all rows from the most recent (not the oldest archive!) table `t`.

**Comment by midenok** [comment] 2017-10-04 14:38
Duplicate of #128.

**Closed as completed by midenok** 2017-10-04 14:38 UTC
Labels: bug
